### ISSUE TITLE
Error when upgrading from v3 to v4

### ISSUE THREAD

**Issue by cb-eli** [retyui/clean-css-loader#20]
Hi, 
I just upgraded from v3 to v4 and I receive the following error when running webpack:

```
  ERROR in ./node_modules/toastr/build/toastr.min.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/clean-css-loader/lib/index.js??ruleSet[1].rules[2].use[2]!./node_modules/toastr/build/toastr.min.css)
  Module build failed (from ./node_modules/clean-css-loader/lib/index.js):
  TypeError: (0 , schema_utils_1.validate) is not a function
      at Object.cleanCssLoader (D:\XXXXXXX\XXXXXXX\XXXXXXX\XXXXXXX\XXXXXXX\node_modules\clean-css-loader\lib\index.js:20:31)
   @ ./node_modules/toastr/build/toastr.min.css 8:6-186 22:17-24 26:0-156 26:0-156 27:22-29 27:33-47 27:50-64
   @ ./Scripts/XXXXXXX/XXXXXXX.js 11:26-13:32
   @ ./Scripts/XXXXXXX/XXXXXXX/XXXXXXX/XXXXXXX/XXXXXXX.jsx 6:0-37 44:8-21
   @ ./Scripts/XXXXXXX/XXXXXXX/XXXXXXX/XXXXXXX/XXXXXXX.jsx 15:0-80 44:27-44
   @ ./Scripts/XXXXXXX/XXXXXXX.js 15:0-87 65:4-25
```

toastr.min.css is not the only CSS file that fails to build. Other files as well, this is just an example.
When I downgrade back to v3.0.0 everything is working.

Any suggestions?
Thanks!

**Comment by retyui** [comment]
What version of webpack do you use?

```bash
npm list webpack schema-utils
```


To fix your error:

```bash
yarn add -D schema-utils
# or npm install -D schema-utils
```

**Comment by cb-eli** [comment]
```
+-- babel-loader@8.2.2
| `-- schema-utils@2.7.1
`-- webpack@5.58.2
  +-- schema-utils@3.1.1
  `-- terser-webpack-plugin@5.2.4
    `-- schema-utils@3.1.1
```

Should I install `schema-utils@3.1.1`?

**Comment by retyui** [comment]
Yes, install the latest 3.x.x 


I will fix it soon

**Comment by retyui** [comment]
Fixed in [4.1.1 diff...](https://npmfs.com/compare/clean-css-loader/4.1.0/4.1.1/)

**Comment by cb-eli** [comment]
1. Thanks for the fix, errors disappeared and the build is successfully passed.
2. Now I'm receiving the following warning:
```
  WARNING in ./node_modules/bootstrap-select/dist/css/bootstrap-select.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/clean-css-loader/lib/index.js??ruleSet[1].rules[2].use[2]!./node_modules/bootstrap-select/dist/css/bootstrap-select.css)
  Module Warning (from ./node_modules/clean-css-loader/lib/index.js):
  Ignoring local source map at "D:\Projects\XXXXX\XXXXX\XXXXX\XXXXX\bootstrap-select.css.map" as resource is missing.
   @ ./node_modules/bootstrap-select/dist/css/bootstrap-select.css 8:6-198 22:17-24 26:0-168 26:0-168 27:22-29 27:33-47 27:50-64
   @ ./Scripts/XXXXX/XXXXX.js 3:0-56
   @ ./Scripts/XXXXX/XXXXX/XXXXX/XXXXX.js 2:0-34
```
Any idea what's causing this warning?

**Comment by retyui** [comment]
I need time to investigate it
